### ISSUE TITLE
Error while loading shared libraries: libnotify.so.4: no such file or directory

### ISSUE THREAD

**Issue by ZvikaZ** [electron/electron-api-demos#219] opened 2016-06-07 11:17 UTC
Trying to run Electron API Demos on SLES11, failed with:
`./Electron API Demos: error while loading shared libraries: libnotify.so.4: cannot open shared object file: No such file or directory
`

My system details:

> $ lsb_release -a
LSB Version:    core-2.0-noarch:core-3.2-noarch:core-4.0-noarch:core-2.0-x86_64:core-3.2-x86_64:core-4.0-x86_64:desktop-4.0-amd64:desktop-4.0-noarch:graphics-2.0-amd64:graphics-2.0-noarch:graphics-3.2-amd64:graphics-3.2-noarch:graphics-4.0-amd64:graphics-4.0-noarch
Distributor ID: SUSE LINUX
Description:    SUSE Linux Enterprise Server 11 (x86_64)
Release:        11
Codename:       n/a

It seems to be related to this:
https://github.com/cgrossde/Pullover/issues/24

But I couldn't use that information to solve my problem.

According to their [wiki](https://github.com/cgrossde/Pullover/wiki/Installing-on-Linux) it seems that there should be different Unix releases for 32 and 64 bits.

**Comment by jlord** [comment] 2016-08-22 21:07
Have you had any more luck with this? Are you able to install `libnotify.so.4` manually?

**Comment by ZvikaZ** [comment] 2016-08-23 06:59
Didn't succeed.
And anyway, after seeing that such an important issue went without any reply from the Electron team, I gave up evaluating it.
It's a nice project, but probably not ready yet for production, with such problems and no support.

**Comment by jlord** [comment] 2016-08-23 23:09
I'm not able to reproduce this and am not familiar enough with this environment. Perhaps someone else will be able to chime in.

**Comment by ZvikaZ** [comment] 2016-08-24 06:39
"Can't reproduce" is much better than no reply...
Anyway, in what distros did you try to reproduce?

**Comment by jlord** [comment] 2016-08-24 17:42
@ZvikaZ This is likely a bug with Electron itself. Can you try installing the dependency? https://software.opensuse.org/package/libnotify4 or via a package manager.

Cross 🔗 to related issue https://github.com/electron/electron/issues/5348

**Comment by jlord** [comment] 2016-09-07 18:04
Closing this out here as it's not an issue with the Demos app specifically.

**Closed by jlord** 2016-09-07 18:04 UTC
Labels: Linux
