### ISSUE TITLE
How to make window Settings match the actual size

### ISSUE THREAD

**Issue by y489436672** [electron/electron-api-demos#330] opened 2017-10-19 10:22 UTC
* What operating system are you using? 
win7  X64
* What version of Node.js is on your system?
v 8.4.0
When I created a new window, the actual size of the window was always about 1.25 times the size of the window, and I saw that the devicePixelRatio of the window was 1.25, which was generated after the release of the electron 1.4.16.How do I do that?

**Comment by MarshallOfSound** [comment] 2017-10-19 10:40
Closing as duplicate of https://github.com/electron/electron/issues/9560

**Closed** 2017-10-19 10:59 UTC
